/**
 * ISO 27001:2022 Annex A Controls — All 93 Controls
 * Organized by 4 themes: Organizational, People, Physical, Technological
 */

export const ANNEX_A = [
  {
    id: "A5",
    theme: "Organizational",
    icon: "🏢",
    color: "#3498db",
    count: 37,
    controls: [
      { id: "5.1", name: "Policies for information security", desc: "Management-approved information security policies must be published and communicated", priority: "critical" },
      { id: "5.2", name: "Information security roles & responsibilities", desc: "Define and allocate information security roles and responsibilities", priority: "critical" },
      { id: "5.3", name: "Segregation of duties", desc: "Conflicting duties and areas of responsibility shall be segregated", priority: "high" },
      { id: "5.4", name: "Management responsibilities", desc: "Management shall require all personnel to apply information security per established policies", priority: "critical" },
      { id: "5.5", name: "Contact with authorities", desc: "Establish and maintain contact with relevant authorities", priority: "medium" },
      { id: "5.6", name: "Contact with special interest groups", desc: "Establish contact with special interest groups or security forums", priority: "low" },
      { id: "5.7", name: "Threat intelligence", desc: "Collect and analyse information about threats to information security", priority: "high", isNew: true },
      { id: "5.8", name: "Information security in project management", desc: "Integrate information security into project management", priority: "high" },
      { id: "5.9", name: "Inventory of information & assets", desc: "Develop and maintain an inventory of information and other associated assets", priority: "critical" },
      { id: "5.10", name: "Acceptable use of information & assets", desc: "Rules for acceptable use of information and assets shall be identified and documented", priority: "high" },
      { id: "5.11", name: "Return of assets", desc: "Personnel shall return all organizational assets upon termination", priority: "medium" },
      { id: "5.12", name: "Classification of information", desc: "Information shall be classified according to business needs and impact", priority: "high" },
      { id: "5.13", name: "Labelling of information", desc: "Appropriate set of procedures for labelling information", priority: "medium" },
      { id: "5.14", name: "Information transfer", desc: "Transfer rules, agreements, or procedures for all types of transfer facilities", priority: "high" },
      { id: "5.15", name: "Access control", desc: "Rules to control physical and logical access to information and assets", priority: "critical" },
      { id: "5.16", name: "Identity management", desc: "Full lifecycle of identities shall be managed", priority: "critical" },
      { id: "5.17", name: "Authentication information", desc: "Allocation and management of authentication information shall be controlled", priority: "critical" },
      { id: "5.18", name: "Access rights", desc: "Access rights shall be provisioned, reviewed, modified and removed", priority: "critical" },
      { id: "5.19", name: "Information security in supplier relationships", desc: "Processes to manage information security risks associated with suppliers", priority: "high" },
      { id: "5.20", name: "Addressing info security in supplier agreements", desc: "Relevant security requirements established with each supplier", priority: "high" },
      { id: "5.21", name: "Managing info security in the ICT supply chain", desc: "Processes to manage information security risks in ICT supply chain", priority: "high" },
      { id: "5.22", name: "Monitoring & review of supplier services", desc: "Regularly monitor, review and audit supplier service delivery", priority: "medium" },
      { id: "5.23", name: "Information security for cloud services", desc: "Processes for acquisition, use, management and exit from cloud services", priority: "high", isNew: true },
      { id: "5.24", name: "Incident management planning & preparation", desc: "Plan and prepare for managing information security incidents", priority: "critical" },
      { id: "5.25", name: "Assessment & decision on info security events", desc: "Assess security events and decide if they are security incidents", priority: "high" },
      { id: "5.26", name: "Response to info security incidents", desc: "Respond to information security incidents according to documented procedures", priority: "critical" },
      { id: "5.27", name: "Learning from info security incidents", desc: "Knowledge gained from incidents shall be used to strengthen controls", priority: "high" },
      { id: "5.28", name: "Collection of evidence", desc: "Establish procedures for identification, collection and preservation of evidence", priority: "medium" },
      { id: "5.29", name: "Info security during disruption", desc: "Plan how to maintain security during disruption", priority: "high" },
      { id: "5.30", name: "ICT readiness for business continuity", desc: "ICT readiness shall be planned, implemented and tested", priority: "high", isNew: true },
      { id: "5.31", name: "Legal, statutory & contractual requirements", desc: "Identify and document requirements relevant to information security", priority: "critical" },
      { id: "5.32", name: "Intellectual property rights", desc: "Implement appropriate procedures to protect intellectual property rights", priority: "medium" },
      { id: "5.33", name: "Protection of records", desc: "Records shall be protected from loss, destruction and falsification", priority: "high" },
      { id: "5.34", name: "Privacy & protection of PII", desc: "Ensure privacy and protection of personally identifiable information", priority: "critical" },
      { id: "5.35", name: "Independent review of info security", desc: "Approach to managing information security shall be independently reviewed", priority: "high" },
      { id: "5.36", name: "Compliance with policies & standards", desc: "Compliance with the organization's security policies shall be regularly reviewed", priority: "high" },
      { id: "5.37", name: "Documented operating procedures", desc: "Operating procedures for information processing facilities shall be documented", priority: "high" },
    ],
  },
  {
    id: "A6",
    theme: "People",
    icon: "👥",
    color: "#2ecc71",
    count: 8,
    controls: [
      { id: "6.1", name: "Screening", desc: "Background verification checks on all candidates shall be carried out", priority: "high" },
      { id: "6.2", name: "Terms & conditions of employment", desc: "Employment agreements shall state personnel's responsibilities for info security", priority: "critical" },
      { id: "6.3", name: "Info security awareness, education & training", desc: "Personnel shall receive appropriate awareness training and regular updates", priority: "critical" },
      { id: "6.4", name: "Disciplinary process", desc: "A formal disciplinary process shall be communicated for security policy violations", priority: "medium" },
      { id: "6.5", name: "Responsibilities after termination", desc: "Info security responsibilities that remain valid after termination shall be defined", priority: "medium" },
      { id: "6.6", name: "Confidentiality or non-disclosure agreements", desc: "Agreements reflecting the organization's needs for protection of information", priority: "high" },
      { id: "6.7", name: "Remote working", desc: "Security measures for remote working shall be implemented", priority: "high" },
      { id: "6.8", name: "Info security event reporting", desc: "Mechanism for personnel to report observed security events timely", priority: "critical" },
    ],
  },
  {
    id: "A7",
    theme: "Physical",
    icon: "🏗️",
    color: "#f39c12",
    count: 14,
    controls: [
      { id: "7.1", name: "Physical security perimeters", desc: "Security perimeters shall be defined and used to protect sensitive areas", priority: "high" },
      { id: "7.2", name: "Physical entry", desc: "Secure areas shall be protected by appropriate entry controls", priority: "high" },
      { id: "7.3", name: "Securing offices, rooms & facilities", desc: "Physical security for offices, rooms and facilities shall be designed and applied", priority: "medium" },
      { id: "7.4", name: "Physical security monitoring", desc: "Premises shall be continuously monitored for unauthorized access", priority: "high", isNew: true },
      { id: "7.5", name: "Protecting against physical threats", desc: "Protection against physical and environmental threats shall be designed", priority: "medium" },
      { id: "7.6", name: "Working in secure areas", desc: "Security measures for working in secure areas shall be designed and implemented", priority: "medium" },
      { id: "7.7", name: "Clear desk & clear screen", desc: "Clear desk rules for papers and clear screen rules for information processing", priority: "medium" },
      { id: "7.8", name: "Equipment siting & protection", desc: "Equipment shall be sited and protected to reduce environmental threats", priority: "medium" },
      { id: "7.9", name: "Security of assets off-premises", desc: "Off-site assets shall be protected", priority: "medium" },
      { id: "7.10", name: "Storage media", desc: "Storage media shall be managed through their lifecycle", priority: "high" },
      { id: "7.11", name: "Supporting utilities", desc: "Information processing facilities shall be protected from power failures", priority: "medium" },
      { id: "7.12", name: "Cabling security", desc: "Cables carrying power or data shall be protected from interception or damage", priority: "low" },
      { id: "7.13", name: "Equipment maintenance", desc: "Equipment shall be maintained correctly to ensure availability and integrity", priority: "medium" },
      { id: "7.14", name: "Secure disposal or re-use of equipment", desc: "Items of equipment containing storage media shall be verified", priority: "high" },
    ],
  },
  {
    id: "A8",
    theme: "Technological",
    icon: "💻",
    color: "#9b59b6",
    count: 34,
    controls: [
      { id: "8.1", name: "User endpoint devices", desc: "Information stored on, processed by or accessible via endpoint devices shall be protected", priority: "high" },
      { id: "8.2", name: "Privileged access rights", desc: "Allocation and use of privileged access rights shall be restricted and managed", priority: "critical" },
      { id: "8.3", name: "Information access restriction", desc: "Access to information shall be restricted in accordance with the access control policy", priority: "critical" },
      { id: "8.4", name: "Access to source code", desc: "Read and write access to source code and development tools shall be managed", priority: "high" },
      { id: "8.5", name: "Secure authentication", desc: "Secure authentication technologies and procedures shall be established", priority: "critical" },
      { id: "8.6", name: "Capacity management", desc: "Use of resources shall be monitored and adjusted", priority: "medium" },
      { id: "8.7", name: "Protection against malware", desc: "Protection against malware shall be implemented with user awareness", priority: "critical" },
      { id: "8.8", name: "Management of technical vulnerabilities", desc: "Information about technical vulnerabilities shall be obtained and action taken", priority: "critical" },
      { id: "8.9", name: "Configuration management", desc: "Configurations including security configurations shall be established and managed", priority: "high", isNew: true },
      { id: "8.10", name: "Information deletion", desc: "Information stored in systems and devices shall be deleted when no longer required", priority: "high", isNew: true },
      { id: "8.11", name: "Data masking", desc: "Data masking shall be used in accordance with the access control policy", priority: "medium", isNew: true },
      { id: "8.12", name: "Data leakage prevention", desc: "Data leakage prevention measures shall be applied to systems and networks", priority: "high", isNew: true },
      { id: "8.13", name: "Information backup", desc: "Backup copies of information, software and systems shall be maintained and tested", priority: "critical" },
      { id: "8.14", name: "Redundancy of information processing", desc: "Information processing facilities shall be implemented with sufficient redundancy", priority: "high" },
      { id: "8.15", name: "Logging", desc: "Logs that record activities, exceptions, faults and other events shall be produced and stored", priority: "critical" },
      { id: "8.16", name: "Monitoring activities", desc: "Networks, systems and applications shall be monitored for anomalous behaviour", priority: "high", isNew: true },
      { id: "8.17", name: "Clock synchronization", desc: "Clocks of information processing systems shall be synchronized", priority: "low" },
      { id: "8.18", name: "Use of privileged utility programs", desc: "Use of utility programs capable of overriding controls shall be restricted", priority: "medium" },
      { id: "8.19", name: "Installation of software on operational systems", desc: "Procedures shall be implemented to securely manage software installation", priority: "high" },
      { id: "8.20", name: "Networks security", desc: "Networks and network devices shall be secured, managed and controlled", priority: "critical" },
      { id: "8.21", name: "Security of network services", desc: "Security mechanisms, service levels and requirements of network services shall be identified", priority: "high" },
      { id: "8.22", name: "Segregation of networks", desc: "Groups of information services, users and systems shall be segregated", priority: "high" },
      { id: "8.23", name: "Web filtering", desc: "Access to external websites shall be managed to reduce exposure to malicious content", priority: "medium", isNew: true },
      { id: "8.24", name: "Use of cryptography", desc: "Rules for effective use of cryptography shall be defined and implemented", priority: "critical" },
      { id: "8.25", name: "Secure development life cycle", desc: "Rules for secure development of software and systems shall be established", priority: "high" },
      { id: "8.26", name: "Application security requirements", desc: "Information security requirements shall be identified when developing applications", priority: "high" },
      { id: "8.27", name: "Secure system architecture & engineering", desc: "Principles for engineering secure systems shall be established and applied", priority: "high" },
      { id: "8.28", name: "Secure coding", desc: "Secure coding principles shall be applied to software development", priority: "high", isNew: true },
      { id: "8.29", name: "Security testing in development & acceptance", desc: "Security testing processes shall be defined and implemented", priority: "high" },
      { id: "8.30", name: "Outsourced development", desc: "The organization shall direct, monitor and review outsourced system development", priority: "medium" },
      { id: "8.31", name: "Separation of development, test & production", desc: "Development, testing and production environments shall be separated", priority: "high" },
      { id: "8.32", name: "Change management", desc: "Changes to information processing facilities and systems shall be subject to change management", priority: "critical" },
      { id: "8.33", name: "Test information", desc: "Test information shall be appropriately selected, protected and managed", priority: "medium" },
      { id: "8.34", name: "Protection during audit testing", desc: "Audit tests and other assurance activities shall be planned and agreed", priority: "low" },
    ],
  },
];

export const TOTAL_CONTROLS = 93;
